### ISSUE TITLE
Change color skin

### ISSUE THREAD

**Issue by lugorcorp** [Atnic/laravel-admin-lte#3]
Hi, what can I do to change the color skin of the template? I'm changing the blue option to green or red, but nothing happens.

Can you help me?

Btw, I'm using your project in a SPA application and is working like a charm, nice job.

**Comment by lugorcorp** [comment]
Nvm, I found the solution. Seems like this instruction has nothing to do with the color: `config('admin-lte.skin', 'blue')`

You have to hardcode the color template here: `config/admin-lte.php`

**Comment by frdteknikelektro** [comment]
Actually ini Laravel, config('admin-lte.skin', 'blue') means if you don't specify 'admin-lte.skin' than it callback to blue.

👍
